---
- hosts: workerk8s1
  become: yes
  tasks:
  - name: Restart kubelet
    service:
      name: kubelet
      daemon_reload: yes
      state: restarted

  - name: Copy the join command to server location
    copy: src=join-command dest=/tmp/join-command.sh mode=0777

  - name: Join the node to cluster (Debian)
    shell: /tmp/join-command.sh
    when: ansible_os_family == "Debian"

  - name: Join the node to cluster (RedHat)
    shell: |
      kubeadm reset -f
      echo -n " --ignore-preflight-errors=all"  >> /tmp/join-command.sh
      sh /tmp/join-command.sh
    when: ansible_os_family == "RedHat"