wCount = 1

Vagrant.configure("2") do |config|

  config.vm.define "masterk8s" do |masterk8s|
    masterk8s.vm.box = "centos/7"
    masterk8s.vm.hostname = "masternode"
    masterk8s.vm.network "private_network", ip: "192.168.88.100"
    masterk8s.vm.synced_folder "../", "/var/www/vagrant", type: "rsync"
  end

  (1..wCount).each do |i|
    config.vm.define "workerk8s#{i}" do |workerk8s|
      workerk8s.vm.box = "centos/7"
      workerk8s.vm.hostname = "workernode#{i}"
      workerk8s.vm.network "private_network", ip: "192.168.88.10#{i}"
      workerk8s.vm.synced_folder "../", "/var/www/vagrant", type: "rsync"
    end
  end

  config.vm.provision "shell", path: "../script.sh"
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook-k8s.yml"
  end
  config.vm.provider "virtualbox" do |vb|
      vb.cpus = 2
      vb.memory = "2048"
  end
  
end
